# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWdg.ui'
#
# Created: Mon Jul  5 16:20:14 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWdg(object):
    def setupUi(self, MainWdg):
        MainWdg.setObjectName("MainWdg")
        MainWdg.resize(483, 470)
        self.centralwidget = QtGui.QWidget(MainWdg)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 461, 398))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.originalImg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.originalImg.setObjectName("originalImg")
        self.horizontalLayout.addWidget(self.originalImg)
        spacerItem = QtGui.QSpacerItem(220, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.previewImg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.previewImg.setObjectName("previewImg")
        self.horizontalLayout.addWidget(self.previewImg)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWdg.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWdg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 483, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Actions = QtGui.QMenu(self.menubar)
        self.menu_Actions.setObjectName("menu_Actions")
        MainWdg.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWdg)
        self.statusbar.setObjectName("statusbar")
        MainWdg.setStatusBar(self.statusbar)
        self.openAct = QtGui.QAction(MainWdg)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/document-open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAct.setIcon(icon)
        self.openAct.setObjectName("openAct")
        self.quitAct = QtGui.QAction(MainWdg)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAct.setIcon(icon1)
        self.quitAct.setObjectName("quitAct")
        self.flipXYAct = QtGui.QAction(MainWdg)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/xy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flipXYAct.setIcon(icon2)
        self.flipXYAct.setObjectName("flipXYAct")
        self.flipXZAct = QtGui.QAction(MainWdg)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/xz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flipXZAct.setIcon(icon3)
        self.flipXZAct.setObjectName("flipXZAct")
        self.flipYZAct = QtGui.QAction(MainWdg)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/yz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flipYZAct.setIcon(icon4)
        self.flipYZAct.setObjectName("flipYZAct")
        self.saveAct = QtGui.QAction(MainWdg)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAct.setIcon(icon5)
        self.saveAct.setObjectName("saveAct")
        self.menuFile.addAction(self.openAct)
        self.menuFile.addAction(self.saveAct)
        self.menuFile.addAction(self.quitAct)
        self.menu_Actions.addAction(self.flipXYAct)
        self.menu_Actions.addAction(self.flipXZAct)
        self.menu_Actions.addAction(self.flipYZAct)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Actions.menuAction())

        self.retranslateUi(MainWdg)
        QtCore.QMetaObject.connectSlotsByName(MainWdg)

    def retranslateUi(self, MainWdg):
        MainWdg.setWindowTitle(QtGui.QApplication.translate("MainWdg", "Flip Normals - godlike@ancient-ritual.com", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWdg", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Actions.setTitle(QtGui.QApplication.translate("MainWdg", "&Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.openAct.setText(QtGui.QApplication.translate("MainWdg", "&Open Image", None, QtGui.QApplication.UnicodeUTF8))
        self.openAct.setShortcut(QtGui.QApplication.translate("MainWdg", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAct.setText(QtGui.QApplication.translate("MainWdg", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAct.setShortcut(QtGui.QApplication.translate("MainWdg", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.flipXYAct.setText(QtGui.QApplication.translate("MainWdg", "Flip X,Y", None, QtGui.QApplication.UnicodeUTF8))
        self.flipXZAct.setText(QtGui.QApplication.translate("MainWdg", "Flip X,Z", None, QtGui.QApplication.UnicodeUTF8))
        self.flipYZAct.setText(QtGui.QApplication.translate("MainWdg", "Flip Y,Z", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAct.setText(QtGui.QApplication.translate("MainWdg", "&Save Image", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAct.setShortcut(QtGui.QApplication.translate("MainWdg", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
