######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 6 17:16:51 2010
######################################################################

QT=core script
CONFIG+=debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyObject.h MyObject2.h
SOURCES += Main.cpp
